export const skills = [
  { label: "Java", value: "Java" },
  { label: "JavaScript", value: "JavaScript" },
  { label: "Python", value: "Python" },
  { label: "Go", value: "Go" },
  { label: "Rust", value: "Rust" },
  { label: "C++", value: "C++" },
  { label: "C", value: "C" },
  { label: "React", value: "React" },
  { label: "Angular", value: "Angular" },
  { label: "Vue.js", value: "Vue.js" },
  { label: "Node.js", value: "Node.js" },
  { label: "Express.js", value: "Express.js" },
  { label: "Spring Boot", value: "Spring Boot" },
  { label: "Django", value: "Django" },
  { label: "Flask", value: "Flask" },
  { label: "Ruby", value: "Ruby" },
  { label: "Rails", value: "Rails" },
  { label: "PHP", value: "PHP" },
  { label: "Laravel", value: "Laravel" },
  { label: "ASP.NET", value: "ASP.NET" },
  { label: "React Native", value: "React Native" },
  { label: "Swift", value: "Swift" },
  { label: "Kotlin", value: "Kotlin" },
  { label: "Flutter", value: "Flutter" },
  { label: "Android", value: "Android" },
  { label: "iOS", value: "iOS" },
  { label: "TensorFlow", value: "TensorFlow" },
  { label: "PyTorch", value: "PyTorch" },
  { label: "Keras", value: "Keras" },
  { label: "Scikit-learn", value: "Scikit-learn" },
  { label: "Pandas", value: "Pandas" },
  { label: "NumPy", value: "NumPy" },
  { label: "Matplotlib", value: "Matplotlib" },
  { label: "Seaborn", value: "Seaborn" },
  { label: "Jupyter", value: "Jupyter" },
  { label: "D3.js", value: "D3.js" },
  { label: "Plotly", value: "Plotly" },
  { label: "Bokeh", value: "Bokeh" },
  { label: "GraphQL", value: "GraphQL" },
  { label: "RESTful API", value: "RESTful API" },
  { label: "MongoDB", value: "MongoDB" },
  { label: "MySQL", value: "MySQL" },
  { label: "PostgreSQL", value: "PostgreSQL" },
  { label: "SQLite", value: "SQLite" },
  { label: "Redis", value: "Redis" },
  { label: "Elasticsearch", value: "Elasticsearch" },
  { label: "Kafka", value: "Kafka" },
  { label: "RabbitMQ", value: "RabbitMQ" },
  { label: "Flask-SQLAlchemy", value: "Flask-SQLAlchemy" },
  { label: "Hibernate", value: "Hibernate" },
  { label: "JUnit", value: "JUnit" },
  { label: "JUnit Jupiter", value: "JUnit Jupiter" },
  { label: "TestNG", value: "TestNG" },
  { label: "Selenium", value: "Selenium" },
  { label: "Cucumber", value: "Cucumber" },
  { label: "Jest", value: "Jest" },
  { label: "Mocha", value: "Mocha" },
  { label: "Chai", value: "Chai" },
  { label: "Redux", value: "Redux" },
  { label: "MobX", value: "MobX" },
  { label: "RxJS", value: "RxJS" },
  { label: "jQuery", value: "jQuery" },
  { label: "Bootstrap", value: "Bootstrap" },
  { label: "Tailwind CSS", value: "Tailwind CSS" },
  { label: "Sass", value: "Sass" },
  { label: "Less", value: "Less" },
  { label: "Webpack", value: "Webpack" },
  { label: "Babel", value: "Babel" },
  { label: "ESLint", value: "ESLint" },
  { label: "Prettier", value: "Prettier" },
  { label: "Jenkins", value: "Jenkins" },
  { label: "Travis CI", value: "Travis CI" },
  { label: "Git", value: "Git" },
  { label: "GitHub", value: "GitHub" },
  { label: "GitLab", value: "GitLab" },
  { label: "Bitbucket", value: "Bitbucket" },
  { label: "Docker", value: "Docker" },
  { label: "Kubernetes", value: "Kubernetes" },
  { label: "Helm", value: "Helm" },
  { label: "Ansible", value: "Ansible" },
  { label: "Terraform", value: "Terraform" },
  { label: "AWS", value: "AWS" },
  { label: "Azure", value: "Azure" },
  { label: "Google Cloud", value: "Google Cloud" },
  { label: "Heroku", value: "Heroku" },
  { label: "DigitalOcean", value: "DigitalOcean" },
  { label: "Netlify", value: "Netlify" },
  { label: "Vercel", value: "Vercel" },
  { label: "Nginx", value: "Nginx" },
  { label: "Apache", value: "Apache" },
];

// [
//   { label: "Java", value: "Java" },
//   { label: "Javascript", value: "Javascript" },
//   { label: "Python", value: "Typescript" },
//   { label: "Golang", value: "Golang" },
//   { label: "Rust", value: "Rust" },
//   { label: "C++", value: "C++" },
//   { label: "C", value: "C" },
//   { label: "Reactjs", value: "Reactjs" },
//   { label: "Nextjs", value: "Nextjs" },
//   { label: "DSA", value: "DSA" },
//   { label: "Algorithms", value: "Algorithms" },
//   { label: "System Design", value: "System Design" },
//   { label: "Data Structures", value: "Data Structures" },
// ];
