export const skills = [
  {
    label: "Java",
    value: "Java",
    pun: "The 'byte' of programming everyone loves.",
  },
  {
    label: "JavaScript",
    value: "JavaScript",
    pun: "Where every 'function' matters.",
  },
  {
    label: "Python",
    value: "Python",
    pun: "The 'snake'-ily elegant language of ML.",
  },
  { label: "Go", value: "Go", pun: "Where coding 'speed' meets efficiency." },
  { label: "Rust", value: "Rust", pun: "For when you need 'rust'-proof code." },
  {
    label: "C++",
    value: "C++",
    pun: "Taking programming to the 'next' level.",
  },
  { label: "C", value: "C", pun: "The 'foundation' of all programming." },
  { label: "React", value: "React", pun: "Adding 'components' to your UI." },
  {
    label: "Angular",
    value: "Angular",
    pun: "For 'angles' in web development.",
  },
  { label: "Vue.js", value: "Vue.js", pun: "A 'vue' of frontend simplicity." },
  {
    label: "Node.js",
    value: "Node.js",
    pun: "Where 'node' meets backend brilliance.",
  },
  {
    label: "Express.js",
    value: "Express.js",
    pun: "Speeding up 'express' development.",
  },
  {
    label: "Spring Boot",
    value: "Spring Boot",
    pun: "Springing into 'boot'-iful backend.",
  },
  {
    label: "Django",
    value: "Django",
    pun: "Building 'django'-nificent web apps.",
  },
  {
    label: "Flask",
    value: "Flask",
    pun: "A 'flask' of simplicity for web development.",
  },
  { label: "Ruby", value: "Ruby", pun: "Shining bright like a 'ruby' gem." },
  {
    label: "Rails",
    value: "Rails",
    pun: "Riding the 'rails' of web development.",
  },
  {
    label: "PHP",
    value: "PHP",
    pun: "For 'php'eeling dynamic web experiences.",
  },
  {
    label: "Laravel",
    value: "Laravel",
    pun: "Crafting 'laravel'-ous web apps.",
  },
  {
    label: "ASP.NET",
    value: "ASP.NET",
    pun: "The '.NET' way to web development.",
  },
  {
    label: "React Native",
    value: "React Native",
    pun: "Bringing 'native' mobile to React.",
  },
  { label: "Swift", value: "Swift", pun: "Swiftly coding iOS apps." },
  {
    label: "Kotlin",
    value: "Kotlin",
    pun: "A 'kotlin' of fun in Android development.",
  },
  {
    label: "Flutter",
    value: "Flutter",
    pun: "Fluttering into cross-platform apps.",
  },
  {
    label: "Android",
    value: "Android",
    pun: "Where 'android' dreams become apps.",
  },
  {
    label: "iOS",
    value: "iOS",
    pun: "Crafting 'iOS'tellar mobile experiences.",
  },
  {
    label: "TensorFlow",
    value: "TensorFlow",
    pun: "Adding 'flow' to machine learning.",
  },
  {
    label: "PyTorch",
    value: "PyTorch",
    pun: "Illuminating AI with 'py'torch.",
  },
  {
    label: "Keras",
    value: "Keras",
    pun: "A 'keras' of simplicity in deep learning.",
  },
  {
    label: "Scikit-learn",
    value: "Scikit-learn",
    pun: "Learning ML with 'scikit'-ease.",
  },
  { label: "Pandas", value: "Pandas", pun: "The 'panda' of data analysis." },
  {
    label: "NumPy",
    value: "NumPy",
    pun: "Making arrays feel right at home in Python! ",
  },
  { label: "Matplotlib", value: "Matplotlib", pun: "The 'plot'ting champion." },
  {
    label: "Seaborn",
    value: "Seaborn",
    pun: "Seaborn-ing data visualization.",
  },
  {
    label: "Jupyter",
    value: "Jupyter",
    pun: "Where 'jupyter' ideas come alive.",
  },
  { label: "D3.js", value: "D3.js", pun: "Drawing with 'd3'elight." },
  { label: "Plotly", value: "Plotly", pun: "Plotting with 'plot'ential." },
  {
    label: "Bokeh",
    value: "Bokeh",
    pun: "Creating 'bokeh'-tiful visualizations.",
  },
  {
    label: "GraphQL",
    value: "GraphQL",
    pun: "Querying with 'graph'ical precision.",
  },
  {
    label: "RESTful API",
    value: "RESTful API",
    pun: "The 'REST'ful route to APIs.",
  },
  { label: "MongoDB", value: "MongoDB", pun: "Where 'mongo' meets databases." },
  { label: "MySQL", value: "MySQL", pun: "The 'mySQL'ution to data storage." },
  {
    label: "PostgreSQL",
    value: "PostgreSQL",
    pun: "A 'post'ively powerful database.",
  },
  { label: "SQLite", value: "SQLite", pun: "A 'lite'weight database choice." },
  { label: "Redis", value: "Redis", pun: "Rediscovering fast data caching." },
  {
    label: "Elasticsearch",
    value: "Elasticsearch",
    pun: "Seeking data with 'elastic'ity.",
  },
  { label: "Kafka", value: "Kafka", pun: "Streamlining data with 'kafka'." },
  {
    label: "RabbitMQ",
    value: "RabbitMQ",
    pun: "Hopping into 'rabbit' messaging.",
  },
  {
    label: "Flask-SQLAlchemy",
    value: "Flask-SQLAlchemy",
    pun: "A 'flask' of SQL power.",
  },
  {
    label: "Hibernate",
    value: "Hibernate",
    pun: "Hibernate-ing data effortlessly.",
  },
  { label: "JUnit", value: "JUnit", pun: "Uniting tests with 'junit'." },
  {
    label: "JUnit Jupiter",
    value: "JUnit Jupiter",
    pun: "Exploring 'jupiter' in testing.",
  },
  {
    label: "TestNG",
    value: "TestNG",
    pun: "Testing with a 'test'ament to NG.",
  },
  {
    label: "Selenium",
    value: "Selenium",
    pun: "Navigating the web with 'selenium'.",
  },
  {
    label: "Cucumber",
    value: "Cucumber",
    pun: "Crispy testing with 'cucumber'.",
  },
  { label: "Jest", value: "Jest", pun: "Jesting around with 'jest'." },
  { label: "Mocha", value: "Mocha", pun: "A 'mocha' of testing flavor." },
  { label: "Chai", value: "Chai", pun: "Brewing assertions with 'chai'." },
  { label: "Redux", value: "Redux", pun: "The 'redux' of state management." },
  { label: "MobX", value: "MobX", pun: "Mobbing state with 'mobx'." },
  { label: "RxJS", value: "RxJS", pun: "Reacting to events with 'rxjs'." },
  { label: "jQuery", value: "jQuery", pun: "Querying DOMs with 'jquery'." },
  { label: "Bootstrap", value: "Bootstrap", pun: "Bootstrapping stylish UIs." },
  {
    label: "Tailwind CSS",
    value: "Tailwind CSS",
    pun: "Riding the 'tailwind' of CSS.",
  },
  { label: "Sass", value: "Sass", pun: "Adding 'sass' to your styles." },
  { label: "Less", value: "Less", pun: "Less is more with 'less'." },
  {
    label: "Webpack",
    value: "Webpack",
    pun: "Packing bundles with 'webpack'.",
  },
  { label: "Babel", value: "Babel", pun: "Transpiling like a 'babel' fish." },
  { label: "ESLint", value: "ESLint", pun: "Linting code the 'eslint' way." },
  {
    label: "Prettier",
    value: "Prettier",
    pun: "Making code 'prettier' than ever.",
  },
  {
    label: "Jenkins",
    value: "Jenkins",
    pun: "Automating builds with 'jenkins'.",
  },
  {
    label: "Travis CI",
    value: "Travis CI",
    pun: "Testing and building with 'travis'.",
  },
  { label: "Git", value: "Git", pun: "Committing changes with 'git'." },
  { label: "GitHub", value: "GitHub", pun: "Hosting code with 'github'." },
  { label: "GitLab", value: "GitLab", pun: "Labbing code with 'gitlab'." },
  {
    label: "Bitbucket",
    value: "Bitbucket",
    pun: "Stashing code in 'bitbucket'.",
  },
  {
    label: "Docker",
    value: "Docker",
    pun: "Containerizing apps with 'docker'.",
  },
  {
    label: "Kubernetes",
    value: "Kubernetes",
    pun: "Sailing the 'kubernetes' seas.",
  },
  { label: "Helm", value: "Helm", pun: "Navigating deployments with 'helm'." },
  {
    label: "Ansible",
    value: "Ansible",
    pun: "Playing orchestral deployments with 'ansible'.",
  },
  {
    label: "Terraform",
    value: "Terraform",
    pun: "Building worlds with 'terraform'.",
  },
  { label: "AWS", value: "AWS", pun: "Raining services with 'AWS'." },
  {
    label: "Azure",
    value: "Azure",
    pun: "Blue-skying deployments with 'azure'.",
  },
  {
    label: "Google Cloud",
    value: "Google Cloud",
    pun: "Cloud nine with 'Google Cloud'.",
  },
  { label: "Heroku", value: "Heroku", pun: "Scaling heights with 'heroku'." },
  {
    label: "DigitalOcean",
    value: "DigitalOcean",
    pun: "Diving into 'digitalocean' deployments.",
  },
  {
    label: "Netlify",
    value: "Netlify",
    pun: "Netting deployments with 'netlify'.",
  },
  {
    label: "Vercel",
    value: "Vercel",
    pun: "Accelerating with 'vercel' deployments.",
  },
  { label: "Nginx", value: "Nginx", pun: "Serving web traffic with 'nginx'." },
  {
    label: "Apache",
    value: "Apache",
    pun: "Launching websites with 'apache'.",
  },
];

// [
//   { label: "Java", value: "Java" },
//   { label: "Javascript", value: "Javascript" },
//   { label: "Python", value: "Typescript" },
//   { label: "Golang", value: "Golang" },
//   { label: "Rust", value: "Rust" },
//   { label: "C++", value: "C++" },
//   { label: "C", value: "C" },
//   { label: "Reactjs", value: "Reactjs" },
//   { label: "Nextjs", value: "Nextjs" },
//   { label: "DSA", value: "DSA" },
//   { label: "Algorithms", value: "Algorithms" },
//   { label: "System Design", value: "System Design" },
//   { label: "Data Structures", value: "Data Structures" },
// ];
